# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e22113d69df163f994a0361c8e3cfc68f9ab4a5b94c09102cc0d8fa67286d3782db000b3369baf019622066c3dc13d568fe5e3b0e5da3790b89141bdcdddecc

test:
  secret_key_base: 2553e63808313ccd6a95ed17a0d89aee9a61f9df1e3ff6bd87141988ed11a2657a54658e9904bcb43b67f1ca2464a69fcd0294b6f5b35bb2ac9627a1fe3cf578

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
